namespace ColorLinesNG2 {
	public interface IStrings {
		string Achieve10Desc { get; }
		string Achieve13Desc { get; }
		string Achieve500Desc { get; }
		string Achieve1000Desc { get; }
		string AchieveBlowReward { get; }
		string AchieveScoreReward { get; }
		string Achievement { get; }
		string Achievements { get; }
		string Animations { get; }
		string ApplicationName { get; }
		string Back { get; }
		string BackgroundSelected { get; }
		string BallsSkinSelected { get; }
		string CompleteAchievement { get; }
		string CompleteTutorial { get; }
		string ConfirmMove { get; }
		string Exit { get; }
		string ExitQ { get; }
		string Gallery { get; }
		string FirstReward { get; }
		string GameOver { get; }
		string Hi { get; }
		string Menu { get; }
		string Music { get; }
		string Name { get; }
		string NewRecord { get; }
		string Next { get; }
		string No { get; }
		string Restart { get; }
		string RestartQ { get; }
		string RestoredGame { get; }
		string Results { get; }
		string Reward { get; }
		string RewardLocked { get; }
		string Route { get; }
		string SelectBackground { get; }
		string SelectBallsSkin { get; }
		string Settings { get; }
		string Skip { get; }
		string Sounds { get; }
		string TapMe { get; }
		string TutBlocked { get; }
		string TutMakeLine { get; }
		string TutTapBall { get; }
		string TutTapBlock { get; }
		string Yes { get; }
	}
}