//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorLinesNG2 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
					string prefix;
#if __ANDROID__
					prefix = "ColorLinesNG2.Droid.";
#elif __IOS__
					prefix = "ColorLinesNG2.iOS.";
#endif
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(prefix + "Strings", typeof(StringsShared).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		///   Looks up a localized string similar to POP 10 BALLS.
		/// </summary>
		internal static string Achieve10Desc {
			get {
				return ResourceManager.GetString("Achieve10Desc", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to POP 13 BALLS.
		/// </summary>
		internal static string Achieve13Desc {
			get {
				return ResourceManager.GetString("Achieve13Desc", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SCORE 500 POINTS.
		/// </summary>
		internal static string Achieve500Desc {
			get {
				return ResourceManager.GetString("Achieve500Desc", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SCORE 1000 POINTS.
		/// </summary>
		internal static string Achieve1000Desc {
			get {
				return ResourceManager.GetString("Achieve1000Desc", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to NEW BALL COLORS.
		/// </summary>
		internal static string AchieveBlowReward {
			get {
				return ResourceManager.GetString("AchieveBlowReward", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to NEW BACKGROUND.
		/// </summary>
		internal static string AchieveScoreReward {
			get {
				return ResourceManager.GetString("AchieveScoreReward", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ACHIEVEMENT: .
		/// </summary>
		internal static string Achievement {
			get {
				return ResourceManager.GetString("Achievement", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ACHIEVEMENTS.
		/// </summary>
		internal static string Achievements {
			get {
				return ResourceManager.GetString("Achievements", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ANIMATIONS.
		/// </summary>
		internal static string Animations {
            get {
                return ResourceManager.GetString("Animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Lines NG.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to CURRENT BACKGROUND.
		/// </summary>
		internal static string BackgroundSelected {
			get {
				return ResourceManager.GetString("BackgroundSelected", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CURRENT COLORS.
		/// </summary>
		internal static string BallsSkinSelected {
			get {
				return ResourceManager.GetString("BallsSkinSelected", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to UNLOCK ACHIEVEMENT: .
		/// </summary>
		internal static string CompleteAchievement {
			get {
				return ResourceManager.GetString("CompleteAchievement", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to COMPLETE A SIMPLE TUTORIAL.
		/// </summary>
		internal static string CompleteTutorial {
            get {
                return ResourceManager.GetString("CompleteTutorial", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to CONFIRM TURN.
		/// </summary>
		internal static string ConfirmMove {
			get {
				return ResourceManager.GetString("ConfirmMove", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to EXIT.
		/// </summary>
		internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT?.
        /// </summary>
        internal static string ExitQ {
            get {
                return ResourceManager.GetString("ExitQ", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to REWARD UNLOCKED IN MENU -> GALLERY.
		/// </summary>
		internal static string FirstReward {
			get {
				return ResourceManager.GetString("FirstReward", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to GALLERY.
		/// </summary>
		internal static string Gallery {
			get {
				return ResourceManager.GetString("Gallery", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to GAME OVER.
		/// </summary>
		internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HI.
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to MENU.
		/// </summary>
		internal static string Menu {
			get {
				return ResourceManager.GetString("Menu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MUSIC.
		/// </summary>
		internal static string Music {
			get {
				return ResourceManager.GetString("Music", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to NAME:.
		/// </summary>
		internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW RECORD!.
        /// </summary>
        internal static string NewRecord {
            get {
                return ResourceManager.GetString("NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT COLORS.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTART.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTART?.
        /// </summary>
        internal static string RestartQ {
            get {
                return ResourceManager.GetString("RestartQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTS.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to REWARD: .
		/// </summary>
		internal static string Reward {
			get {
				return ResourceManager.GetString("Reward", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to REWARD IS LOCKED.
		/// </summary>
		internal static string RewardLocked {
			get {
				return ResourceManager.GetString("RewardLocked", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ROUTE.
		/// </summary>
		internal static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to SELECT THIS BACKGROUND.
		/// </summary>
		internal static string SelectBackground {
			get {
				return ResourceManager.GetString("SelectBackground", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SELECT THESE COLORS.
		/// </summary>
		internal static string SelectBallsSkin {
			get {
				return ResourceManager.GetString("SelectBallsSkin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SETTINGS.
		/// </summary>
		internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIP.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to SOUNDS.
		/// </summary>
		internal static string Sounds {
			get {
				return ResourceManager.GetString("Sounds", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to TAP ME.
		/// </summary>
		internal static string TapMe {
            get {
                return ResourceManager.GetString("TapMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR THE BALL&apos;S PATH.
        /// </summary>
        internal static string TutBlocked {
            get {
                return ResourceManager.GetString("TutBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAKE A LINE OF 5 OR MORE BALLS.
        /// </summary>
        internal static string TutMakeLine {
            get {
                return ResourceManager.GetString("TutMakeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAP A GREEN BALL TO SELECT.
        /// </summary>
        internal static string TutTapBall {
            get {
                return ResourceManager.GetString("TutTapBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAP AN EMPTY BLOCK TO MOVE.
        /// </summary>
        internal static string TutTapBlock {
            get {
                return ResourceManager.GetString("TutTapBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

//	readit
//	REMINDER: ADD iOS TRANSLATION INTO iOS PROJECTS STRINGS
//	yes, readit

    }
}
